# Generated by Django 5.1.6 on 2025-02-16 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acortador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlacortadas',
            old_name='url_acortada',
            new_name='codigo',
        ),
    ]
