# Generated by Django 5.1.6 on 2025-02-16 03:13

import Acortador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acortador', '0002_rename_url_acortada_urlacortadas_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlacortadas',
            name='codigo',
            field=models.TextField(default=Acortador.models.generar_codigo, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='urlacortadas',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
